# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build and Release

on:
    pull_request:
        branches: 'main'
        types:
            - closed
env:
    GH_TOKEN: ${{ github.token}}

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.x] # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'

            # Set outputs
            - name: Set outputs
              id: vars
              run: echo "commit_sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
            - name: Check outputs
              run: echo ${{ steps.vars.outputs.commit_sha_short }}

            # Provide GH creds
            - run: git config user.name "${{ github.actor }}"
            - run: git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"

            # Get up-to-date info from remote
            - run: git fetch --all

            # Merge main into release
            - run: git checkout main
            - run: git pull

            # Checkout release branch
            - run: git checkout release
            - run: git pull

            # Merge main into release
            - run: git merge main

            # Install dependencies
            - run: npm ci

            # Build
            - run: npm run build --if-present

            # Add /dist to release branch
            - run: git add dist

            # Create env file
            - run: git rm -r --ignore-unmatch .env
            - run: echo "COMMIT_SHA_SHORT=${{ steps.vars.outputs.commit_sha_short }}" > .env
            - run: git add -f .env

            # Delete obsolete files/dirs
            # - run: git rm -r --ignore-unmatch .vscode postman swagger test .babelrc .env.example .eslintrc.json .prettierrc jest.config.ts

            # Commit changes
            - run: git commit -m "Build release ${{ steps.vars.outputs.commit_sha_short }}"

            # Push release branch
            - run: git push --set-upstream origin release

            ## Create release
            - run: gh release create ${{ steps.vars.outputs.commit_sha_short }}
                  --generate-notes
