# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
    pull_request:
        branches: 'main'
        types:
            - closed

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.x] # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'

            # Set outputs
            - name: Set outputs
              id: vars
              run: echo "commit_sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
            - name: Check outputs
              run: echo ${{ steps.vars.outputs.commit_sha_short }}

            # Install dependencies
            - run: npm ci

            # Build
            - run: npm run build --if-present

            # Provide GH creds
            - run: git config user.email "hellosimonhudson@gmail.com"
            - run: git config user.name "Simon Hudson"

            # Add and Push /dist to main branch
            - run: git add dist
            - run: git commit -m "build dist"
            - run: git push

            # Create a new release branch off main
            - run: git checkout -b release/${{ steps.vars.outputs.commit_sha_short }}
            - run: git push origin release/${{ steps.vars.outputs.commit_sha_short }}

            ## Create release
            - run: git release create ${{ steps.vars.outputs.commit_sha_short }} --title ${{ steps.vars.outputs.commit_sha_short }} --notes "Pull Request \#${{ github.event.number }}"

            # Remove /dist from main branch
            - run: git checkout main
            - run: git rm -r dist
            - run: git commit -m "remove dist"
            - run: git push
