# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Unit tests
on:
    push:
    pull_request:
        branches: 'main'
        types:
            - opened

env:
    GH_TOKEN: ${{ github.token}}

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.x] # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'

            # Install dependencies
            - run: npm ci

            # Create .env file
            - name: Create .env file
              run: echo "DB_URI=mongodb+srv://foo:bar" > .env

            # Run tests
            - run: npm run test
